name: Debug Push Events

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Push Event Information
        shell: bash
        run: |
          echo "🔍 PUSH EVENT DEBUG INFORMATION"
          echo "================================="
          echo ""
          echo "📋 GitHub Context:"
          echo "  - Event name: ${{ github.event_name }}"
          echo "  - Actor: ${{ github.actor }}"
          echo "  - Repository: ${{ github.repository }}"
          echo "  - Ref: ${{ github.ref }}"
          echo "  - SHA: ${{ github.sha }}"
          echo "  - Run ID: ${{ github.run_id }}"
          echo "  - Run number: ${{ github.run_number }}"
          echo ""
          echo "📋 Push Event Details:"
          echo "  - Pushed by: ${{ github.event.pusher.name }}"
          echo "  - Pusher email: ${{ github.event.pusher.email }}"
          echo "  - Head commit SHA: ${{ github.event.head_commit.id }}"
          echo "  - Head commit message: ${{ github.event.head_commit.message }}"
          echo "  - Head commit author: ${{ github.event.head_commit.author.name }}"
          echo "  - Head commit author email: ${{ github.event.head_commit.author.email }}"
          echo "  - Head commit committer: ${{ github.event.head_commit.committer.name }}"
          echo "  - Head commit committer email: ${{ github.event.head_commit.committer.email }}"
          echo ""
          echo "📋 Git Repository State:"
          echo "  - Current HEAD: $(git rev-parse HEAD)"
          echo "  - Latest commit author: $(git log -1 --pretty=format:'%an')"
          echo "  - Latest commit email: $(git log -1 --pretty=format:'%ae')"
          echo "  - Latest commit message: $(git log -1 --pretty=format:'%s')"
          echo "  - Latest commit SHA: $(git log -1 --pretty=format:'%H')"
          echo ""
          echo "📋 Last 3 commits:"
          git log -3 --oneline --pretty=format:'  %h - %an <%ae> - %s'
          echo ""
          echo ""
          echo "📋 Raw GitHub Event JSON (first 2000 chars):"
          echo '${{ toJson(github.event) }}' | head -c 2000
          echo ""
          echo "================================="

      - name: Check Dependabot Detection Logic
        shell: bash
        run: |
          echo "🔍 TESTING DEPENDABOT DETECTION"
          echo "================================"
          
          # Test the same logic as your Dependabot Release Action
          commit_author=$(git log -1 --pretty=format:'%an')
          echo "Latest commit author: '$commit_author'"
          
          if [[ "$commit_author" == "dependabot[bot]" ]]; then
            echo "✅ WOULD PROCEED - Dependabot commit detected"
          else
            echo "❌ WOULD SKIP - Not a Dependabot commit"
          fi
          
          echo ""
          echo "Checking recent commits for Dependabot:"
          git log -5 --pretty=format:'%an - %s' | while read line; do
            if [[ "$line" == dependabot[bot]* ]]; then
              echo "  ✅ $line"
            else
              echo "  ❌ $line"
            fi
          done